package parameters;

public class ParametersConfig {
	
	public String INDEX;

	// SimulationController
	public int SIMULATIONS;
	public int CYCLES_PER_SIMULATION;

	public int AGENT_FIRM_CAPITAL_Q;
	public int AGENT_FIRM_CAPITAL_NW;
	public float AGENT_FIRM_CAPITAL_MARGIN;
	public float AGENT_FIRM_CAPITAL_RD_PROPENSITY;
	public float AGENT_FIRM_CAPITAL_FRACTION_X;
	public float AGENT_FIRM_CAPITAL_Z_IN;
	public float AGENT_FIRM_CAPITAL_Z_IM;
	public float AGENT_FIRM_CAPITAL_PRODUCTIVITY_A_MIN;
	public float AGENT_FIRM_CAPITAL_PRODUCTIVITY_A_MAX;
	public float AGENT_FIRM_CAPITAL_PRODUCTIVITY_B_MIN;
	public float AGENT_FIRM_CAPITAL_PRODUCTIVITY_B_MAX;
	public int AGENT_FIRM_CAPITAL_BROCHURES;
	
	public int AGENT_FIRM_CONSUMER_Q;
	public int AGENT_FIRM_CONSUMER_STOCK_SPARE;
	public float AGENT_FIRM_CONSUMER_MARGIN;
	public float AGENT_FIRM_CONSUMER_CAPITAL_INTENSITY;
	public int AGENT_FIRM_CONSUMER_NW;
	public int AGENT_FIRM_CONSUMER_PAYBACK_PERIOD;
	public int AGENT_FIRM_CONSUMER_COMPETITIVITY_PRICE_W1;
	public int AGENT_FIRM_CONSUMER_COMPETITIVITY_UNFILLED_W2;
	public int AGENT_FIRM_CONSUMER_OBSOLETE;
	public float COMPETITIVITY_MARKETSHARE;
	
	
	public int AGENT_PERSON;
	public float AGENT_PERSON_EXPEND;
	
	// AgentGovernment
	public float AGENT_GOVERNMENT_EMPLOYEE_TAX;
	public float AGENT_GOVERNMENT_FIRM_TAX;
	public float AGENT_GOVERNMENT_UNEMPLOYED_WAGE;
	public int WORLD_WAGE;
	public float PS1;
	public float PS2;

	
	// AgentFirmCapital

	public boolean PRINT_DEBUG;
//	public final static String PATH = "/home/miglesia/Documents/Econ/Simu/";
	public String PATH;

	public void setSimulationParameters(){
		Parameters.INDEX = this.INDEX;
		Parameters.CYCLES_PER_SIMULATION = this.CYCLES_PER_SIMULATION;
		Parameters.SIMULATIONS = this.SIMULATIONS;
		Parameters.PRINT_DEBUG = this.PRINT_DEBUG;
		Parameters.PATH = this.PATH;
		Parameters.AGENT_FIRM_CAPITAL_Q = this.AGENT_FIRM_CAPITAL_Q;
		Parameters.AGENT_FIRM_CAPITAL_NW = this.AGENT_FIRM_CAPITAL_NW;
		Parameters.AGENT_FIRM_CAPITAL_MARGIN = this.AGENT_FIRM_CAPITAL_MARGIN;
		Parameters.AGENT_FIRM_CAPITAL_RD_PROPENSITY = this.AGENT_FIRM_CAPITAL_RD_PROPENSITY;
		Parameters.AGENT_FIRM_CAPITAL_FRACTION_X = this.AGENT_FIRM_CAPITAL_FRACTION_X;
		Parameters.AGENT_FIRM_CAPITAL_Z_IN = this.AGENT_FIRM_CAPITAL_Z_IN;
		Parameters.AGENT_FIRM_CAPITAL_Z_IM = this.AGENT_FIRM_CAPITAL_Z_IM;
		Parameters.AGENT_FIRM_CAPITAL_PRODUCTIVITY_A_MIN = this.AGENT_FIRM_CAPITAL_PRODUCTIVITY_A_MIN;
		Parameters.AGENT_FIRM_CAPITAL_PRODUCTIVITY_A_MAX = this.AGENT_FIRM_CAPITAL_PRODUCTIVITY_A_MAX;
		Parameters.AGENT_FIRM_CAPITAL_PRODUCTIVITY_B_MIN = this.AGENT_FIRM_CAPITAL_PRODUCTIVITY_B_MIN;
		Parameters.AGENT_FIRM_CAPITAL_PRODUCTIVITY_B_MAX = this.AGENT_FIRM_CAPITAL_PRODUCTIVITY_B_MAX;
		Parameters.AGENT_FIRM_CAPITAL_BROCHURES = this.AGENT_FIRM_CAPITAL_BROCHURES;
		Parameters.AGENT_FIRM_CONSUMER_Q = this.AGENT_FIRM_CONSUMER_Q;
		Parameters.AGENT_FIRM_CONSUMER_STOCK_SPARE = this.AGENT_FIRM_CONSUMER_STOCK_SPARE;
		Parameters.AGENT_FIRM_CONSUMER_MARGIN = this.AGENT_FIRM_CONSUMER_MARGIN;
		Parameters.AGENT_FIRM_CONSUMER_CAPITAL_INTENSITY = this.AGENT_FIRM_CONSUMER_CAPITAL_INTENSITY;
		Parameters.AGENT_FIRM_CONSUMER_NW = this.AGENT_FIRM_CONSUMER_NW;
		Parameters.AGENT_FIRM_CONSUMER_PAYBACK_PERIOD = this.AGENT_FIRM_CONSUMER_PAYBACK_PERIOD;
		Parameters.AGENT_FIRM_CONSUMER_COMPETITIVITY_PRICE_W1 = this.AGENT_FIRM_CONSUMER_COMPETITIVITY_PRICE_W1;
		Parameters.AGENT_FIRM_CONSUMER_COMPETITIVITY_UNFILLED_W2 = this.AGENT_FIRM_CONSUMER_COMPETITIVITY_UNFILLED_W2;
		Parameters.AGENT_FIRM_CONSUMER_OBSOLETE = this.AGENT_FIRM_CONSUMER_OBSOLETE;
		Parameters.COMPETITIVITY_MARKETSHARE = this.COMPETITIVITY_MARKETSHARE;
		Parameters.AGENT_PERSON = this.AGENT_PERSON;
		Parameters.AGENT_PERSON_EXPEND = this.AGENT_PERSON_EXPEND;
		Parameters.AGENT_GOVERNMENT_EMPLOYEE_TAX = this.AGENT_GOVERNMENT_EMPLOYEE_TAX;
		Parameters.AGENT_GOVERNMENT_FIRM_TAX = this.AGENT_GOVERNMENT_FIRM_TAX;
		Parameters.AGENT_GOVERNMENT_UNEMPLOYED_WAGE = this.AGENT_GOVERNMENT_UNEMPLOYED_WAGE;
		Parameters.WORLD_WAGE = this.WORLD_WAGE;
		Parameters.PS1 = this.PS1;
		Parameters.PS2 = this.PS2;

	}

}
